language: go

go:
- "1.11.x"

branches:
  only:
  - master
  - develop

env:
- GO111MODULE=on

services:
- mysql

before_install:
- pwd

install:
- pwd

script:
- GOARCH=386 go test -v ./...
- GOARCH=amd64 go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic


after_success:
- bash <(curl -s https://codecov.io/bash)



