language: go

go:
  - "1.11.x"
  - "1.12.x"

branches:
  only:
  - master
  - develop

env:
  - GO111MODULE=on

services:
  - mysql

before_install:
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('12345678') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - service mysql restart

install:
  - pwd

script:
  - cd g
  - GOARCH=386 go test -v ./...
  - GOARCH=amd64 go test -v ./... -race -coverprofile=coverage.txt -covermode=atomic


after_success:
  - bash <(curl -s https://codecov.io/bash)



